feat: initial files
adelsonsljunior/my-little-garden-backend pull request #1
Opened 2023-07-27 11:09 UTC by guilherme-gjv

# Description

Project bootstrap made with https://start.spring.io/

## Project 
- Maven

## Spring Version
- 3.1.2 (default)

## Language
- Java

## Java Version
- 17

## Packaging
- .jar

## Dependencies
- Spring Web
- Spring Data JPA
- PostgreSQL Driver
- Validation

2023-07-30 21:05 UTC, adelsonsljunior requested changes
### Pasta [mylittlegarden](https://github.com/adelsonsljunior/my-little-garden-backend/tree/app-bootstrap/mylittlegarden)

Mover e conteído da pasta [mylittlegarden](https://github.com/adelsonsljunior/my-little-garden-backend/tree/app-bootstrap/mylittlegarden), na raiz do projeto, e em seguida apagar a mesma.

### Organização dos pacotes

o pacote `mylittlegarden` tá duplicado, na [main](https://github.com/adelsonsljunior/my-little-garden-backend/tree/app-bootstrap/mylittlegarden/src/main) e na [test](https://github.com/adelsonsljunior/my-little-garden-backend/tree/app-bootstrap/mylittlegarden/src/test/java/com/api/mylittlegarden/mylittlegarden). Reorganizar para que o pacote fique como `com.api.mylittlegarden`.

2023-08-05 02:49 UTC, guilherme-gjv commented
please, cheque se a dependência é essa mesmo :D
(não como testá-la)

2023-08-05 15:13 UTC, adelsonsljunior approved these changes

2023-08-05 15:14 UTC, adelsonsljunior commented
Tudo certo :)

2023-08-05 15:14 UTC, merged